language: python
branches:
  only:
  - pelican
install:
  - pip install -r requirements.txt
script:
  - make travis
env:
  global:
    secure: IqTr2/RIIWmA+XI+Z7bBTVUuqx9hV/Hep8Ya7GZ16KK4jpMdjQhAT1x16fjNb23IcuqGcg/9km7/gbwGmhPjLNEMlo7n8g586JDuNc/p5JX/aAFy2SwPyzyn4qCqiFvqpZ2QERtijakrXZJ5C0lTn1ENGJyx2nFh91enxHgLIOk=
