language: python
branches:
  only:
    - pelican
install:
  - pip install -r requirements.txt
script:
  - make travis
env:
  global:
    secure: C4kSwgGbmP+ih92Os+B44TTl7WjHF6VRxy7X5RgSlElHEFrwioGpTb44skfnovvdSX0gFhpKPZYD8R7LKbTkVVsbChEVpRAEPf5PyFT+MmTW3ENiXpDabecSmH1AVtFCV8EkXzw/6mDYihKGpTFIbORj6IOEPBw/pwoe3OOMkrM=
